"""Generate expanded sample data for India Consumer Pulse AI."""
import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent.parent))

OUT = Path(__file__).parent.parent / "data" / "samples" / "sample_consumer_tech.csv"

def r(sub, n):
    return json.dumps({"subreddit": sub, "num_comments": n})

def y(title, channel):
    return json.dumps({"video_title": title, "channel": channel})

def a(product, rating):
    return json.dumps({"product": product, "rating": rating, "verified": True})

def g(pub, headline):
    return json.dumps({"publication": pub, "headline": headline})

RECORDS = [
    # ── REDDIT (25 records) ────────────────────────────────────
    {"date":"2026-04-01","source":"reddit","category":"consumer_tech","brand":"Apple","topic":"AI laptops","url":"https://reddit.com/r/india/comments/r001","author":"user_r001","text":"MacBook Air M3 has been my daily driver for 3 months and I cannot believe how good the battery is. 14 hours easily on mixed workloads. Editing 4K footage in Final Cut Pro runs silently without any fan noise. For creative professionals in India this is the best buy at 1.1 lakh even without EMI. Build quality is unmatched by any Windows laptop at this price.","engagement":234,"raw_metadata":r("india",45)},
    {"date":"2026-04-03","source":"reddit","category":"consumer_tech","brand":"Lenovo","topic":"AI laptops","url":"https://reddit.com/r/suggestalaptop/comments/r002","author":"user_r002","text":"Lenovo ThinkPad X1 Carbon Gen 12 review after 2 months — absolute beast for corporate work. Keyboard is best in class, build quality is exceptional, battery lasts all day. The AI noise cancellation in meetings is genuinely useful. At 1.4 lakh it better be perfect. Service center in Pune is actually responsive unlike HP.","engagement":189,"raw_metadata":r("suggestalaptop",38)},
    {"date":"2026-04-05","source":"reddit","category":"consumer_tech","brand":"Samsung","topic":"smartphone upgrades","url":"https://reddit.com/r/india/comments/r003","author":"user_r003","text":"Galaxy S25 Ultra camera is mind blowing yaar. Shot my cousin's wedding and the photos are better than a dedicated DSLR in most scenarios. AI remaster feature is genuinely useful not just a gimmick. Battery life improved massively versus S24. 1.2 lakh is steep but Samsung holds resale value well in India.","engagement":312,"raw_metadata":r("india",92)},
    {"date":"2026-04-08","source":"reddit","category":"consumer_tech","brand":"HP","topic":"premium laptops","url":"https://reddit.com/r/suggestalaptop/comments/r004","author":"user_r004","text":"HP Spectre x360 14 OLED is stunning but keyboard flex is unacceptable at 1.3 lakh. HP service in tier 2 cities is a disaster. Waited 3 weeks for a palm rest replacement and parts were not available. Dell and Lenovo have much better service infrastructure across India. Would not recommend HP outside metro cities.","engagement":267,"raw_metadata":r("suggestalaptop",61)},
    {"date":"2026-04-10","source":"reddit","category":"consumer_tech","brand":"Dell","topic":"AI laptops","url":"https://reddit.com/r/india/comments/r005","author":"user_r005","text":"Dell XPS 15 AI edition thermal performance is absolutely terrible in Indian summers. Room temperature at 32 degrees and the laptop throttles within 10 minutes of load. Paid 1.15 lakh for this. Dell support said use in cool environment. This is a product designed for European climates not India. Extremely disappointed with after sales response.","engagement":445,"raw_metadata":r("india",134)},
    {"date":"2026-04-12","source":"reddit","category":"consumer_tech","brand":"ASUS","topic":"AI laptops","url":"https://reddit.com/r/IndianGaming/comments/r006","author":"user_r006","text":"ASUS ROG Zephyrus G14 2026 is the best gaming laptop under 1.5 lakh in India hands down. AMD Ryzen 9 plus RTX 4070 combo is incredible. Runs AAA titles at ultra settings. Build quality has improved massively from previous generation. Warranty support in Bangalore is actually quite good.","engagement":298,"raw_metadata":r("IndianGaming",87)},
    {"date":"2026-04-15","source":"reddit","category":"consumer_tech","brand":"OnePlus","topic":"smartphone upgrades","url":"https://reddit.com/r/india/comments/r007","author":"user_r007","text":"Switched from iPhone 14 to OnePlus 13R at 42k and honestly not regretting it. Oxygen OS is clean and responsive. Camera is not iPhone level but very good for the price. Fast charging at 100W is insane — full charge in 25 minutes. Battery life is massive at 6000mAh. Perfect for budget conscious Indian consumers.","engagement":178,"raw_metadata":r("india",54)},
    {"date":"2026-04-17","source":"reddit","category":"consumer_tech","brand":"Acer","topic":"premium laptops","url":"https://reddit.com/r/suggestalaptop/comments/r008","author":"user_r008","text":"Acer Swift X 14 with OLED display is criminally underrated. At 75k you get Ryzen 7 AI processor, stunning 2.8K OLED display and surprisingly good build quality. Yes it is not ThinkPad level but for the price it is amazing value. Battery is decent at 8 hours real world. Acer service has improved considerably in metro cities.","engagement":156,"raw_metadata":r("suggestalaptop",43)},
    {"date":"2026-04-20","source":"reddit","category":"consumer_tech","brand":"Apple","topic":"brand experience","url":"https://reddit.com/r/india/comments/r009","author":"user_r009","text":"Apple India service experience has degraded significantly. My 11 month old MacBook Pro developed keyboard issues and the service center wants 45k claiming liquid damage which is false. No water exposure ever. This is a documented manufacturing defect globally. Apple India just wants to upsell extended warranty. Never again.","engagement":523,"raw_metadata":r("india",198)},
    {"date":"2026-04-22","source":"reddit","category":"consumer_tech","brand":"Lenovo","topic":"brand experience","url":"https://reddit.com/r/IndianGaming/comments/r010","author":"user_r010","text":"Lenovo Legion customer service saved my laptop during warranty. Motherboard failure after 8 months and they replaced it within 5 days without any questions. Doorstep pickup and delivery in Gurgaon. This is what premium after sales service should look like in India. Will always recommend Lenovo for gaming laptops.","engagement":234,"raw_metadata":r("IndianGaming",67)},
    {"date":"2026-04-25","source":"reddit","category":"consumer_tech","brand":"Xiaomi","topic":"smartphone upgrades","url":"https://reddit.com/r/india/comments/r011","author":"user_r011","text":"Xiaomi 15 Ultra is punching way above its weight at 85k. Camera system rivals Samsung and Apple in most real world scenarios. MIUI is more stable than ever. Only issue is resale value is terrible in India. But if you keep the phone 2-3 years it is unbeatable value. India pricing is much better than other flagships.","engagement":267,"raw_metadata":r("india",78)},
    {"date":"2026-04-27","source":"reddit","category":"consumer_tech","brand":"HP","topic":"AI laptops","url":"https://reddit.com/r/IndianGaming/comments/r012","author":"user_r012","text":"HP Omen 16 for gaming under 1 lakh is solid choice but build quality feels cheap compared to ASUS or MSI. Fan noise is absolutely terrible at load — you need headphones. Performance in benchmarks is great but thermal design is not optimized for Indian climate at all. Competitors offer better value at this price point.","engagement":145,"raw_metadata":r("IndianGaming",39)},
    {"date":"2026-04-30","source":"reddit","category":"consumer_tech","brand":"Other","topic":"AI laptops","url":"https://reddit.com/r/suggestalaptop/comments/r013","author":"user_r013","text":"Can someone explain what AI in AI laptops actually does? Bought a Copilot+ PC 6 months ago. AI features that work in India without VPN: exactly none of the marketed ones. Recall is not available, most Copilot features need US account. Just buy a regular laptop and save 15k. The AI premium is pure marketing in India.","engagement":389,"raw_metadata":r("suggestalaptop",156)},
    {"date":"2026-05-02","source":"reddit","category":"consumer_tech","brand":"Dell","topic":"premium laptops","url":"https://reddit.com/r/india/comments/r014","author":"user_r014","text":"Dell support is absolutely pathetic. My XPS 13 keyboard stopped working 14 months after purchase. Just out of warranty by 2 months. Dell India quoted 28k for replacement. This is a known design flaw documented across global forums. They should do a recall or at least offer goodwill repair. Never buying Dell again.","engagement":412,"raw_metadata":r("india",143)},
    {"date":"2026-05-04","source":"reddit","category":"consumer_tech","brand":"Apple","topic":"AI laptops","url":"https://reddit.com/r/india/comments/r015","author":"user_r015","text":"M4 MacBook Pro 14 inch is ridiculous value now at 1.4 lakh for the base model after price revision. Performance that beats gaming laptops at 2 lakh. 22 hours battery in real use not marketing claims. Fan never spins during office work. Only downside is RAM upgrade pricing from Apple is extortion level in India.","engagement":345,"raw_metadata":r("india",112)},
    {"date":"2026-05-06","source":"reddit","category":"consumer_tech","brand":"ASUS","topic":"premium laptops","url":"https://reddit.com/r/suggestalaptop/comments/r016","author":"user_r016","text":"ASUS Zenbook Pro 16 OLED is the best creative workstation laptop in India right now. Display calibration out of the box is exceptional — 100% DCI-P3 coverage. Color grading work is transformed. At 1.1 lakh it is value for professionals. Warranty support in Delhi has been fast and painless.","engagement":223,"raw_metadata":r("suggestalaptop",58)},
    {"date":"2026-05-08","source":"reddit","category":"consumer_tech","brand":"Samsung","topic":"AI laptops","url":"https://reddit.com/r/suggestalaptop/comments/r017","author":"user_r017","text":"Samsung Galaxy Book 4 Ultra is massively underrated in India. Intel Core Ultra 9 plus RTX 4070 in a slim 1.8kg body is engineering marvel. AMOLED display is better than anything MacBook offers. Price at 1.6 lakh is high but it competes with Dell XPS and HP Spectre at much better value proposition.","engagement":178,"raw_metadata":r("suggestalaptop",47)},
    {"date":"2026-05-09","source":"reddit","category":"consumer_tech","brand":"Acer","topic":"AI laptops","url":"https://reddit.com/r/IndianGaming/comments/r018","author":"user_r018","text":"Acer Predator Helios Neo 16 at 85k is unbeatable gaming value in India. RTX 4060 performance at this price point is crazy. Yes build quality is average and fan noise is loud. But pure performance per rupee nothing comes close. For students who want gaming on budget this is the answer in 2026.","engagement":234,"raw_metadata":r("IndianGaming",72)},
    {"date":"2026-05-10","source":"reddit","category":"consumer_tech","brand":"OnePlus","topic":"brand experience","url":"https://reddit.com/r/india/comments/r019","author":"user_r019","text":"OnePlus has completely lost its way. Original formula was flagship specs at half price. Now they charge Samsung prices for inferior cameras and worse software support. 3 years OS updates compared to Samsung 7 years is shameful. The community that built this brand is moving to other options.","engagement":312,"raw_metadata":r("india",98)},
    {"date":"2026-05-07","source":"reddit","category":"consumer_tech","brand":"Lenovo","topic":"premium laptops","url":"https://reddit.com/r/suggestalaptop/comments/r020","author":"user_r020","text":"Lenovo IdeaPad Slim 5 at 52k is the best budget laptop for students in India. Build quality is surprisingly solid. Performance with Ryzen 5 is perfect for college work. Battery life at 10 hours is excellent. Lenovo has absolutely nailed the budget segment. No complaints after 4 months of daily use.","engagement":167,"raw_metadata":r("suggestalaptop",34)},
    {"date":"2026-04-13","source":"reddit","category":"consumer_tech","brand":"Apple","topic":"pricing","url":"https://reddit.com/r/india/comments/r021","author":"user_r021","text":"Apple India pricing is a joke compared to US pricing. iPhone 16 Pro costs 1.35 lakh here versus 999 dollars which is 83k at current exchange. We pay 60% premium. No cost EMI makes it feel affordable but we are paying more than any other market. Apple needs India specific pricing like they do for services.","engagement":678,"raw_metadata":r("india",234)},
    {"date":"2026-04-18","source":"reddit","category":"consumer_tech","brand":"Dell","topic":"brand experience","url":"https://reddit.com/r/india/comments/r022","author":"user_r022","text":"Dell India has worst after sales service among premium laptop brands. 4 service center visits for the same overheating issue on XPS 15. Each time they say repaired and problem comes back in 2 weeks. At 1.15 lakh this is completely unacceptable. Filing consumer complaint next. HP and Lenovo are better options.","engagement":534,"raw_metadata":r("india",178)},
    {"date":"2026-04-24","source":"reddit","category":"consumer_tech","brand":"Xiaomi","topic":"smartphone upgrades","url":"https://reddit.com/r/india/comments/r023","author":"user_r023","text":"Redmi Note 14 Pro at 26k is absurd value. 200MP camera, 5500mAh battery, 67W charging, AMOLED display. This is what budget phones should be. Samsung and OnePlus should be worried at this price point. MIUI has its quirks but camera performance is genuinely flagship level.","engagement":445,"raw_metadata":r("india",156)},
    {"date":"2026-05-01","source":"reddit","category":"consumer_tech","brand":"HP","topic":"brand experience","url":"https://reddit.com/r/india/comments/r024","author":"user_r024","text":"HP has finally announced 150 new service centers in tier 2 and 3 Indian cities. This is huge news. HP laptops are excellent hardware but poor service availability outside metros has been their biggest weakness. If they execute this properly they can compete with Lenovo on after sales experience.","engagement":234,"raw_metadata":r("india",67)},
    {"date":"2026-05-03","source":"reddit","category":"consumer_tech","brand":"ASUS","topic":"pricing","url":"https://reddit.com/r/suggestalaptop/comments/r025","author":"user_r025","text":"ASUS has the best price to performance ratio in Indian laptop market right now. Whether budget Vivobook or premium Zenbook the value per rupee beats HP Dell and Samsung consistently. The only brand that matches them at gaming laptops is Lenovo Legion. ASUS needs to improve service center coverage in smaller cities though.","engagement":289,"raw_metadata":r("suggestalaptop",89)},

    # ── YOUTUBE (20 records) ───────────────────────────────────
    {"date":"2026-04-02","source":"youtube","category":"consumer_tech","brand":"Apple","topic":"AI laptops","url":"https://youtube.com/watch?v=yt001","author":"user_yt001","text":"I have been using MacBook Air M3 for video editing and it handles 4K ProRes like a champ. No heating at all. This thing is a beast bhai. The display is much better than my previous Dell. Battery lasts my entire shoot day easily. Totally worth 1.1 lakh for content creators in India.","engagement":1240,"raw_metadata":y("MacBook Air M3 Review India 2026","TechBurner")},
    {"date":"2026-04-06","source":"youtube","category":"consumer_tech","brand":"Lenovo","topic":"AI laptops","url":"https://youtube.com/watch?v=yt002","author":"user_yt002","text":"ThinkPad X1 Carbon review is spot on. Been using mine for corporate consulting work. Keyboard is genuinely the best I have ever typed on. Build quality is tank level. The AI meeting features actually work in Indian office environments. Worth every rupee at 1.4 lakh for professionals.","engagement":876,"raw_metadata":y("Lenovo ThinkPad X1 Carbon Gen 12 Full Review","Gaurav Chaudhary")},
    {"date":"2026-04-09","source":"youtube","category":"consumer_tech","brand":"Samsung","topic":"smartphone upgrades","url":"https://youtube.com/watch?v=yt003","author":"user_yt003","text":"Galaxy S25 Ultra camera bhai sach mein next level hai. Night shots are crazy good. Video stabilization is best I have seen on any phone. But 1.2 lakh is tough to justify when OnePlus 13 at 70k does 90% of what this does. Hard recommendation for India pricing.","engagement":2340,"raw_metadata":y("Samsung Galaxy S25 Ultra Camera Test India","Technical Guruji")},
    {"date":"2026-04-14","source":"youtube","category":"consumer_tech","brand":"HP","topic":"premium laptops","url":"https://youtube.com/watch?v=yt004","author":"user_yt004","text":"HP Spectre x360 looks gorgeous but real world battery is 6 hours max not 17 hours claimed. In Indian summer the bottom gets very warm. For 1.3 lakh I expected much better thermal management. OLED display is stunning though. Form over function for Indian conditions.","engagement":654,"raw_metadata":y("HP Spectre x360 2026 Honest Review India","Shlok Srivastava Tech")},
    {"date":"2026-04-18","source":"youtube","category":"consumer_tech","brand":"ASUS","topic":"AI laptops","url":"https://youtube.com/watch?v=yt005","author":"user_yt005","text":"ASUS ROG Strix G16 is the laptop of the year for Indian gamers. Runs every game at ultra. The 240Hz display is buttery smooth. Yes it is heavy at 2.5kg but gaming laptops are not meant to be carried everywhere. At 1.1 lakh it destroys the competition. Best gaming laptop India 2026.","engagement":3120,"raw_metadata":y("ASUS ROG Strix G16 Gaming Laptop Review 2026","Mumbiker Nikhil Tech")},
    {"date":"2026-04-23","source":"youtube","category":"consumer_tech","brand":"Dell","topic":"AI laptops","url":"https://youtube.com/watch?v=yt006","author":"user_yt006","text":"Dell XPS 15 overheating issue is real and I tested it myself. At 35 degrees room temperature the CPU throttles to 60% within 15 minutes of sustained workload. This is completely unacceptable for a laptop that costs 1.15 lakh. Dell please fix the thermal paste application in India units.","engagement":987,"raw_metadata":y("Dell XPS 15 AI Overheating Problem Real Test India","C4ETech")},
    {"date":"2026-04-28","source":"youtube","category":"consumer_tech","brand":"Acer","topic":"premium laptops","url":"https://youtube.com/watch?v=yt007","author":"user_yt007","text":"Acer Swift X 14 is best laptop under 80k in India. OLED display at this price is unmatched. Battery is 8 hours real world. Build quality has improved from previous gen. Acer is finally taking premium segment seriously. Compare this to HP or Dell at same price — Acer wins on display and value hands down.","engagement":543,"raw_metadata":y("Acer Swift X 14 2026 Review Best Value OLED Laptop India","Trakin Tech")},
    {"date":"2026-05-01","source":"youtube","category":"consumer_tech","brand":"Apple","topic":"smartphone upgrades","url":"https://youtube.com/watch?v=yt008","author":"user_yt008","text":"iPhone 16 Pro camera is absolutely insane for content creators. The 4K 120fps recording with perfect stabilization is a game changer for reels. Yes it is 1.35 lakh but if content creation is your income this pays for itself quickly. The ProRAW photos are stunning for Instagram.","engagement":4560,"raw_metadata":y("iPhone 16 Pro 1 Month Review India","BB Ki Vines Tech")},
    {"date":"2026-05-03","source":"youtube","category":"consumer_tech","brand":"Xiaomi","topic":"smartphone upgrades","url":"https://youtube.com/watch?v=yt009","author":"user_yt009","text":"Xiaomi 15 Pro camera is genuinely competing with Samsung and iPhone now. The Leica tuning is not just marketing. In this review I compared 50 real photos side by side and Xiaomi won in 40% of cases. At 85k it is incredible value. MIUI is much more stable in 2026.","engagement":2100,"raw_metadata":y("Xiaomi 15 Pro vs Samsung vs iPhone Camera Comparison India","Ishan Agarwal")},
    {"date":"2026-05-05","source":"youtube","category":"consumer_tech","brand":"OnePlus","topic":"smartphone upgrades","url":"https://youtube.com/watch?v=yt010","author":"user_yt010","text":"OnePlus 13 at 70k is still the best Android phone for the price. 50W wireless charging is insane convenience. Camera is not Pixel level but very good. Oxygen OS is the cleanest Android experience. Battery at 6000mAh will get you through 2 full days of moderate use.","engagement":1890,"raw_metadata":y("OnePlus 13 3 Month Real World Review India","Geekyranjit")},
    {"date":"2026-05-07","source":"youtube","category":"consumer_tech","brand":"HP","topic":"AI laptops","url":"https://youtube.com/watch?v=yt011","author":"user_yt011","text":"HP Omen 16 AMD vs Intel gaming benchmark comparison. AMD version wins in content creation tasks. Intel version better for pure gaming. Both have terrible fan noise distracting even with headphones. For this price ASUS gives better cooling solution. HP Omen is average value in 2026 India market.","engagement":765,"raw_metadata":y("HP Omen 16 AMD vs Intel India Gaming Benchmarks 2026","Aniket Kumbhar Tech")},
    {"date":"2026-04-11","source":"youtube","category":"consumer_tech","brand":"Samsung","topic":"AI laptops","url":"https://youtube.com/watch?v=yt012","author":"user_yt012","text":"Samsung Galaxy Book 4 Ultra review — is it worth 1.6 lakh in India? Display is genuinely best I have seen on a Windows laptop. AMOLED with ProScaler technology looks incredible. Performance is flagship tier. But Samsung laptop after sales service in India is non-existent outside major metros. Big concern for buyers.","engagement":834,"raw_metadata":y("Samsung Galaxy Book 4 Ultra India Review 2026","C4ETech")},
    {"date":"2026-04-19","source":"youtube","category":"consumer_tech","brand":"Dell","topic":"brand experience","url":"https://youtube.com/watch?v=yt013","author":"user_yt013","text":"Dell Premium Support is a scam in India. 3 year warranty purchased for 15k extra and when I actually needed support they took 3 weeks to resolve a keyboard issue. The support team is clearly untrained and escalations go nowhere. Stick to Lenovo or ASUS if you care about after sales service in India.","engagement":1230,"raw_metadata":y("Dell Premium Support India My Experience Was Terrible","Tech Principal")},
    {"date":"2026-05-09","source":"youtube","category":"consumer_tech","brand":"ASUS","topic":"premium laptops","url":"https://youtube.com/watch?v=yt014","author":"user_yt014","text":"ASUS Zenbook S 16 is the most underrated laptop in India right now. Ryzen AI 9 processor with dedicated NPU makes every AI task faster. The 3.2K OLED display is gorgeous. At 99k it is priced right. ASUS customer service in Hyderabad fixed my charging port in 2 days. Very impressed overall.","engagement":678,"raw_metadata":y("ASUS Zenbook S 16 Review Hidden Gem India 2026","Beebom")},
    {"date":"2026-04-26","source":"youtube","category":"consumer_tech","brand":"Acer","topic":"AI laptops","url":"https://youtube.com/watch?v=yt015","author":"user_yt015","text":"Acer Predator Helios Neo 16 gaming review — RTX 4060 at 80k is insane value. Thermals are managed excellently even in Indian summer heat. 165Hz display is smooth for gaming. Build quality is solid for the price. This is my top recommendation for Indian gamers on a budget in 2026.","engagement":934,"raw_metadata":y("Acer Predator Helios Neo 16 Gaming Review India 2026","GeekyGamer India")},
    {"date":"2026-04-04","source":"youtube","category":"consumer_tech","brand":"Lenovo","topic":"brand experience","url":"https://youtube.com/watch?v=yt016","author":"user_yt016","text":"Lenovo after sales in India is genuinely best among laptop brands. My IdeaPad had a hinge issue and they picked it up same day in Mumbai and returned it fixed in 3 days. No cost to me under warranty. This is the gold standard of service. Why cannot HP and Dell do the same?","engagement":1456,"raw_metadata":y("Lenovo Service Center India Experience 2026","Tech Mere Bhai")},
    {"date":"2026-05-02","source":"youtube","category":"consumer_tech","brand":"Apple","topic":"pricing","url":"https://youtube.com/watch?v=yt017","author":"user_yt017","text":"Apple India prices are absurd but the No Cost EMI makes it accessible for middle class. I calculated the total cost of my iPhone 16 Pro through HDFC no cost EMI over 18 months — it is actually 8% more expensive than upfront due to processing fees. Always calculate the real EMI cost before buying premium tech in India.","engagement":5670,"raw_metadata":y("Apple iPhone EMI Hidden Costs India 2026","Ankur Warikoo Tech")},
    {"date":"2026-04-16","source":"youtube","category":"consumer_tech","brand":"Xiaomi","topic":"pricing","url":"https://youtube.com/watch?v=yt018","author":"user_yt018","text":"Xiaomi India pricing strategy is genius. They price 20-30% below Samsung and Apple while delivering 85-90% of the experience. For Indian middle class consumers who are value conscious this is the perfect positioning. Redmi sub-brand handles budget segment while Xiaomi numbered series handles aspirational buyers perfectly.","engagement":2890,"raw_metadata":y("Xiaomi vs Samsung Value Comparison India 2026","Technical Dost")},
    {"date":"2026-04-30","source":"youtube","category":"consumer_tech","brand":"OnePlus","topic":"brand experience","url":"https://youtube.com/watch?v=yt019","author":"user_yt019","text":"OnePlus used to be the brand for Indian tech enthusiasts who wanted flagship experience without flagship price. That brand is dead. Now OnePlus charges 70-80k for phones that offer less value than Xiaomi at same price. The community feels betrayed. Where did the Never Settle spirit go?","engagement":3420,"raw_metadata":y("OnePlus Lost Its Way India 2026","Gaurav Chaudhary")},
    {"date":"2026-05-06","source":"youtube","category":"consumer_tech","brand":"Samsung","topic":"pricing","url":"https://youtube.com/watch?v=yt020","author":"user_yt020","text":"Samsung India pricing for Galaxy S25 series is significantly better than iPhone at similar specs. The 7 year update promise is a massive advantage over OnePlus and Xiaomi. If you are buying a phone to keep for 4-5 years Samsung is the safest investment in India premium segment.","engagement":1780,"raw_metadata":y("Samsung Galaxy S25 Value Proposition India 2026","Shlok Srivastava Tech")},

    # ── AMAZON REVIEWS (20 records) ───────────────────────────
    {"date":"2026-04-04","source":"amazon_review","category":"consumer_tech","brand":"Apple","topic":"AI laptops","url":"https://amazon.in/review/amz001","author":"user_amz001","text":"Purchased MacBook Air M3 15 inch from Amazon India. Delivery was fast. Product itself is exceptional — battery life is exactly as claimed. Color accuracy for photo editing is superb. The fanless design means zero noise even during heavy multitasking. Packaging was perfect no damage. Genuine Apple product verified. Worth every paisa.","engagement":234,"raw_metadata":a("Apple MacBook Air M3 15 inch",5)},
    {"date":"2026-04-07","source":"amazon_review","category":"consumer_tech","brand":"Lenovo","topic":"premium laptops","url":"https://amazon.in/review/amz002","author":"user_amz002","text":"Lenovo ThinkPad E14 for office work is solid but battery claims are exaggerated. Amazon says 12 hours I get 7-8 hours in real use. Build quality is excellent as expected from ThinkPad lineage. Keyboard is outstanding. But 7 hours is not a full workday for Indian office conditions. Lenovo should be more honest about India usage.","engagement":156,"raw_metadata":a("Lenovo ThinkPad E14 Gen 5",3)},
    {"date":"2026-04-11","source":"amazon_review","category":"consumer_tech","brand":"Samsung","topic":"smartphone upgrades","url":"https://amazon.in/review/amz003","author":"user_amz003","text":"Samsung Galaxy S25+ is excellent but price is too high for what you get compared to OnePlus. Camera is great, display is best in class, battery life is good. But at 99k the value proposition versus competitors is weak. Samsung should price India market differently. Still a great phone if budget is not a concern.","engagement":89,"raw_metadata":a("Samsung Galaxy S25+",4)},
    {"date":"2026-04-16","source":"amazon_review","category":"consumer_tech","brand":"HP","topic":"premium laptops","url":"https://amazon.in/review/amz004","author":"user_amz004","text":"HP Envy x360 OLED delivered in damaged packaging from Amazon. Hinge was broken on arrival. Amazon return process was smooth but I had to wait 10 days for replacement. The replacement unit is perfect. Display quality is stunning. But quality control issues and packaging failures are concerning for a 90k laptop.","engagement":123,"raw_metadata":a("HP Envy x360 14 OLED",3)},
    {"date":"2026-04-19","source":"amazon_review","category":"consumer_tech","brand":"Dell","topic":"premium laptops","url":"https://amazon.in/review/amz005","author":"user_amz005","text":"Dell Inspiron 16 is best value laptop at 60k on Amazon India. For non-gaming professional work it handles everything perfectly. Battery at 9 hours is excellent for the price. Build quality is above average. Dell service center in Chennai resolved my wifi issue quickly. Very satisfied with purchase and after sales support.","engagement":198,"raw_metadata":a("Dell Inspiron 16 Plus",5)},
    {"date":"2026-04-24","source":"amazon_review","category":"consumer_tech","brand":"ASUS","topic":"AI laptops","url":"https://amazon.in/review/amz006","author":"user_amz006","text":"ASUS Vivobook 16X with AI features is disappointing on the AI side. The advertised AI features barely work in India. Background removal in Teams works, noise cancellation works, nothing else is useful. The core laptop is fine — good display, decent battery, solid performance. But do not buy for AI features specifically.","engagement":167,"raw_metadata":a("ASUS Vivobook 16X OLED",3)},
    {"date":"2026-04-29","source":"amazon_review","category":"consumer_tech","brand":"Acer","topic":"AI laptops","url":"https://amazon.in/review/amz007","author":"user_amz007","text":"Acer Aspire 5 at 48k from Amazon is absolute value king. Ryzen 5 plus 16GB RAM handles everything I throw at it. Display is not the best but acceptable. SSD speeds are fast. Battery at 7 hours is decent. For students and first time laptop buyers this is the best choice under 50k in India currently.","engagement":312,"raw_metadata":a("Acer Aspire 5 Gen 3",5)},
    {"date":"2026-05-02","source":"amazon_review","category":"consumer_tech","brand":"Apple","topic":"smartphone upgrades","url":"https://amazon.in/review/amz008","author":"user_amz008","text":"iPhone 16 from Amazon India with No Cost EMI made it affordable. 3 year EMI at 0% interest with HDFC card is excellent deal. Phone itself is outstanding — camera battery build quality all excellent. Only frustration is Apple not including charger in box at this price point. Performance is seamlessly fast in daily use.","engagement":287,"raw_metadata":a("Apple iPhone 16 128GB",5)},
    {"date":"2026-05-04","source":"amazon_review","category":"consumer_tech","brand":"Xiaomi","topic":"smartphone upgrades","url":"https://amazon.in/review/amz009","author":"user_amz009","text":"Xiaomi 15 is superb value at 65k. Leica cameras are genuinely great. Fast charging at 90W is impressive. Battery life is 2 days easily with my usage. MIUI stability has improved massively. The only complaint is heating during long gaming sessions. Compared to Samsung at same price Xiaomi wins on most counts.","engagement":201,"raw_metadata":a("Xiaomi 15 8GB 256GB",4)},
    {"date":"2026-05-06","source":"amazon_review","category":"consumer_tech","brand":"OnePlus","topic":"smartphone upgrades","url":"https://amazon.in/review/amz010","author":"user_amz010","text":"OnePlus 13R from Amazon with exchange offer was amazing value. Got 20k off my old Samsung. Phone is fast, clean software, great battery. At 35k effective price this is the best budget flagship in India. Camera is not top tier but good enough. Has been 3 months no issues whatsoever. Highly recommended.","engagement":178,"raw_metadata":a("OnePlus 13R 12GB 256GB",5)},
    {"date":"2026-05-08","source":"amazon_review","category":"consumer_tech","brand":"HP","topic":"AI laptops","url":"https://amazon.in/review/amz011","author":"user_amz011","text":"HP Spectre x360 from Amazon is beautiful but quality control is inconsistent. My first unit had dead pixels. Amazon replacement took 12 days. Second unit is perfect. OLED display is gorgeous 2-in-1 functionality is useful battery is good. But at 1.3 lakh you should not face QC issues. HP must improve manufacturing standards.","engagement":145,"raw_metadata":a("HP Spectre x360 14 OLED",3)},
    {"date":"2026-04-13","source":"amazon_review","category":"consumer_tech","brand":"Lenovo","topic":"AI laptops","url":"https://amazon.in/review/amz012","author":"user_amz012","text":"Lenovo Legion 5i Gen 9 is absolute performance per rupee king at 85k. Gaming benchmarks match laptops costing 1.2 lakh. Build quality is not best in class but solid enough. Thermals are managed well with the custom cooling system. 165Hz display makes gaming buttery smooth. Best gaming laptop under 90k India.","engagement":267,"raw_metadata":a("Lenovo Legion 5i Gen 9",5)},
    {"date":"2026-04-20","source":"amazon_review","category":"consumer_tech","brand":"Dell","topic":"AI laptops","url":"https://amazon.in/review/amz013","author":"user_amz013","text":"Dell XPS 13 9350 is premium in design but port selection is insulting at 1.1 lakh. Two Thunderbolt 4 ports and nothing else. You need 3 dongles for basic connectivity in Indian offices. Display is gorgeous and performance is exceptional. But Dell has to stop compromising on ports to keep design slim.","engagement":234,"raw_metadata":a("Dell XPS 13 9350",3)},
    {"date":"2026-04-27","source":"amazon_review","category":"consumer_tech","brand":"ASUS","topic":"premium laptops","url":"https://amazon.in/review/amz014","author":"user_amz014","text":"ASUS ROG Flow X16 is best convertible gaming laptop in India. Touch display gaming is surprisingly fun. 240Hz refresh rate is stunning. RTX 4080 handles every game at ultra settings. Battery in gaming mode is only 2 hours but plugged in this thing is a desktop replacement. Premium but worth it for serious gamers.","engagement":189,"raw_metadata":a("ASUS ROG Flow X16 2026",5)},
    {"date":"2026-05-09","source":"amazon_review","category":"consumer_tech","brand":"Acer","topic":"premium laptops","url":"https://amazon.in/review/amz015","author":"user_amz015","text":"Acer Predator Helios 16 thermal management is best in class for India. Even in 38 degree summer the cooling keeps CPU and GPU at safe temperatures. Gaming performance is exceptional. Build quality is above average. Acer India warranty service in Hyderabad resolved my RAM slot issue in 3 working days. Excellent after sales.","engagement":223,"raw_metadata":a("Acer Predator Helios 16",5)},
    {"date":"2026-04-09","source":"amazon_review","category":"consumer_tech","brand":"Samsung","topic":"AI laptops","url":"https://amazon.in/review/amz016","author":"user_amz016","text":"Samsung Galaxy Book 4 360 for office and creative work is excellent. The AMOLED display makes documents look beautiful. S Pen support is genuinely useful for note-taking in meetings. Build quality is premium. At 85k it is competitively priced versus HP and Dell. Samsung laptop service availability in Kolkata is limited though.","engagement":134,"raw_metadata":a("Samsung Galaxy Book 4 360",4)},
    {"date":"2026-04-21","source":"amazon_review","category":"consumer_tech","brand":"Apple","topic":"brand experience","url":"https://amazon.in/review/amz017","author":"user_amz017","text":"Apple iPhone 15 still holding strong after 18 months. iOS updates have kept it fast and secure. Battery health at 88% after 18 months of daily use is impressive. The resale value on Amazon is also much better than Samsung or OnePlus. Apple ecosystem is genuinely worth paying the premium for long term users.","engagement":456,"raw_metadata":a("Apple iPhone 15 Pro 256GB",5)},
    {"date":"2026-05-01","source":"amazon_review","category":"consumer_tech","brand":"Lenovo","topic":"brand experience","url":"https://amazon.in/review/amz018","author":"user_amz018","text":"Lenovo IdeaPad 5 Pro was delivered damaged from Amazon. Bezel was cracked. Amazon refund was instant — no questions asked. Repurchased the same laptop and the second unit is perfect. Lenovo build quality is excellent. Just be careful about packaging condition before accepting delivery for expensive items.","engagement":167,"raw_metadata":a("Lenovo IdeaPad 5 Pro 16",4)},
    {"date":"2026-04-15","source":"amazon_review","category":"consumer_tech","brand":"Xiaomi","topic":"pricing","url":"https://amazon.in/review/amz019","author":"user_amz019","text":"Xiaomi Pad 6 at 26k from Amazon India is unbeatable tablet value. Display is better than iPad mini at half the price. Performance handles everything including heavy gaming. MIUI for Pad is well optimized. Accessories like keyboard cover are affordably priced too. Xiaomi is destroying the competition in India tablet segment.","engagement":378,"raw_metadata":a("Xiaomi Pad 6 8GB 256GB",5)},
    {"date":"2026-05-05","source":"amazon_review","category":"consumer_tech","brand":"OnePlus","topic":"pricing","url":"https://amazon.in/review/amz020","author":"user_amz020","text":"OnePlus Watch 3 from Amazon is overpriced at 20k. Samsung Galaxy Watch and Noise smartwatches offer better features at lower prices. OnePlus ecosystem lock-in makes the watch much less useful on non-OnePlus Android phones. Not recommended unless you already own OnePlus phone and want tight integration.","engagement":89,"raw_metadata":a("OnePlus Watch 3",2)},

    # ── GOOGLE NEWS (15 records) ───────────────────────────────
    {"date":"2026-04-03","source":"google_news","category":"consumer_tech","brand":"Apple","topic":"AI laptops","url":"https://economictimes.com/tech/news/apple-m4-india","author":"user_gn001","text":"Apple M4 MacBook Pro receives overwhelming response in Indian market as pre-orders exceed initial estimates by 40%. Analysts attribute demand surge to competitive pricing versus Windows AI laptops and strong ecosystem loyalty among Indian creative professionals and students. Apple India has revised upward shipment allocations for Q2 2026.","engagement":0,"raw_metadata":g("The Economic Times","Apple MacBook Pro M4 Pre-orders Surge in India")},
    {"date":"2026-04-10","source":"google_news","category":"consumer_tech","brand":"Samsung","topic":"smartphone upgrades","url":"https://livemint.com/tech/samsung-s25-india","author":"user_gn002","text":"Samsung Galaxy S25 series captures 34% of Indian premium smartphone market in first quarter of 2026 according to IDC India data. Ultra model drives aspirational purchases while S25+ dominates enterprise procurement. Samsung India announces 7-year software update commitment as competitive differentiator against Chinese brands.","engagement":0,"raw_metadata":g("LiveMint","Samsung Dominates India Premium Smartphone Segment in Q1 2026")},
    {"date":"2026-04-17","source":"google_news","category":"consumer_tech","brand":"Lenovo","topic":"AI laptops","url":"https://businessstandard.com/lenovo-india-manufacturing","author":"user_gn003","text":"Lenovo announces expanded India manufacturing commitment with new facility in Puducherry targeting AI laptop components production. The investment of 800 crore rupees signals long term confidence in Indian consumer tech market growth. Lenovo India CEO confirms pricing advantage for locally assembled units expected by Q3 2026.","engagement":0,"raw_metadata":g("Business Standard","Lenovo Expands India Manufacturing for AI Laptops")},
    {"date":"2026-04-24","source":"google_news","category":"consumer_tech","brand":"Dell","topic":"brand experience","url":"https://91mobiles.com/dell-india-service","author":"user_gn004","text":"Dell India faces backlash on social media over XPS 15 thermal throttling complaints in Indian summer conditions. Consumer forums show over 2000 complaints in April 2026 alone. Dell India has announced a service advisory offering complimentary thermal paste replacement for affected units. Critics say the acknowledgment came too late.","engagement":0,"raw_metadata":g("91mobiles","Dell XPS 15 Overheating Issue Prompts Service Advisory in India")},
    {"date":"2026-05-01","source":"google_news","category":"consumer_tech","brand":"ASUS","topic":"AI laptops","url":"https://gadgets360.com/asus-india-growth","author":"user_gn005","text":"ASUS reports 45% year on year growth in India gaming laptop segment for fiscal 2025-26. ROG and TUF gaming brands have captured combined market share of 28% in laptops above 80k price segment. ASUS India MD attributes success to localized pricing strategy and expanded tier 2 city service centers.","engagement":0,"raw_metadata":g("Gadgets360","ASUS Reports Record Growth in India Gaming Laptop Market")},
    {"date":"2026-05-05","source":"google_news","category":"consumer_tech","brand":"OnePlus","topic":"brand experience","url":"https://gadgets360.com/oneplus-india-decline","author":"user_gn006","text":"OnePlus India sales decline 22% year on year in Q1 2026 as brand loses ground to Samsung and Xiaomi in the competitive 40k-80k smartphone segment. Industry analysts cite software update policy and camera performance gap as primary reasons for consumer migration to rival brands. OnePlus rumoured to be planning major strategy reset.","engagement":0,"raw_metadata":g("Gadgets360","OnePlus India Market Share Declines as Competition Intensifies")},
    {"date":"2026-05-08","source":"google_news","category":"consumer_tech","brand":"HP","topic":"brand experience","url":"https://ndtvgadgets.com/hp-india-service","author":"user_gn007","text":"HP India introduces new after sales service initiative with 4 hour response guarantee in top 20 Indian cities for commercial and premium consumer laptops. The initiative follows months of criticism over service delays. HP India Country Manager announces 150 new authorized service centers across tier 2 and tier 3 cities by December 2026.","engagement":0,"raw_metadata":g("NDTV Gadgets","HP India Launches 4-Hour Service Response Initiative")},
    {"date":"2026-05-10","source":"google_news","category":"consumer_tech","brand":"Apple","topic":"brand experience","url":"https://thehindubusinessline.com/apple-bengaluru-store","author":"user_gn008","text":"Apple India opens third retail store in Bengaluru Indiranagar area as part of aggressive India expansion strategy. The 8000 square foot store creates 200 local jobs and features Apple latest product lineup including AI-enhanced MacBook Pro and iPhone 16 series. Apple India targets 15 retail stores by 2027.","engagement":0,"raw_metadata":g("The Hindu BusinessLine","Apple Opens Third India Retail Store in Bengaluru")},
    {"date":"2026-04-08","source":"google_news","category":"consumer_tech","brand":"Xiaomi","topic":"smartphone upgrades","url":"https://financialexpress.com/xiaomi-india-q1","author":"user_gn009","text":"Xiaomi India reclaims top position in overall smartphone shipments for Q1 2026 with 22% market share according to Counterpoint Research. Redmi Note 14 series drives volume while Xiaomi 15 Pro establishes premium credentials. Xiaomi India CEO announces INR 2000 crore R&D investment for localised AI features in Hindi and regional languages.","engagement":0,"raw_metadata":g("Financial Express","Xiaomi Reclaims India Smartphone Market Leadership in Q1 2026")},
    {"date":"2026-04-21","source":"google_news","category":"consumer_tech","brand":"Acer","topic":"premium laptops","url":"https://ettech.com/acer-india-premium-growth","author":"user_gn010","text":"Acer India reports 67% growth in premium laptop segment above 70k driven by Swift X and Predator Helios series. Brand previously known for budget devices is successfully repositioning in Indian market. Acer India MD states brand awareness campaign targeting tier 2 cities showing strong return on investment in sales data.","engagement":0,"raw_metadata":g("Economic Times Tech","Acer India Sees 67% Growth in Premium Laptop Segment")},
    {"date":"2026-04-14","source":"google_news","category":"consumer_tech","brand":"Other","topic":"AI laptops","url":"https://gadgets360.com/ai-laptops-india-reality","author":"user_gn011","text":"AI laptop features remain largely unusable in India market six months after launch of Copilot Plus PC ecosystem. Independent testing by consumer advocacy group reveals 80% of advertised AI features require either VPN or US-based Microsoft account to function. Industry experts urge brands to localize AI capabilities for Indian users.","engagement":0,"raw_metadata":g("Gadgets360","AI Laptop Features Remain Unusable in India Six Months After Launch")},
    {"date":"2026-04-28","source":"google_news","category":"consumer_tech","brand":"Samsung","topic":"pricing","url":"https://livemint.com/samsung-india-emi","author":"user_gn012","text":"Samsung India reports 65% of Galaxy S25 series purchases in India made through no-cost EMI schemes. HDFC and ICICI Bank partnerships drive volume. Average EMI tenure is 12 months at Rs 8500 per month for S25+ model. EMI culture increasingly dominant in Indian premium smartphone segment reshaping how brands structure launch pricing.","engagement":0,"raw_metadata":g("LiveMint","65% of Samsung Galaxy S25 Sales in India Through EMI Schemes")},
    {"date":"2026-05-03","source":"google_news","category":"consumer_tech","brand":"Lenovo","topic":"brand experience","url":"https://indianexpress.com/lenovo-service-india","author":"user_gn013","text":"Lenovo India ranked number one in after-sales service satisfaction among laptop brands for third consecutive year according to IMRB consumer survey. Doorstep pickup service available in 150 cities and average repair turnaround of 4.2 days across warranty claims. Lenovo credits investment in service infrastructure as key competitive advantage.","engagement":0,"raw_metadata":g("Indian Express Tech","Lenovo Ranked Top Laptop Brand for After-Sales Service in India")},
    {"date":"2026-04-05","source":"google_news","category":"consumer_tech","brand":"Apple","topic":"pricing","url":"https://businessstandard.com/apple-india-emi","author":"user_gn014","text":"Apple India sees 45% increase in iPhone 16 series sales through buy-now-pay-later and no-cost EMI schemes in Q1 2026. The company has partnered with 12 Indian banks and NBFCs to make flagship products accessible to aspirational middle class consumers. Apple India GM states EMI strategy key to achieving 15% market share goal in premium segment.","engagement":0,"raw_metadata":g("Business Standard","Apple India iPhone Sales Surge Through EMI Partnerships")},
    {"date":"2026-05-07","source":"google_news","category":"consumer_tech","brand":"Xiaomi","topic":"AI laptops","url":"https://gadgets360.com/xiaomi-laptop-india","author":"user_gn015","text":"Xiaomi enters India laptop market with Mi Notebook Pro series priced at 55k-85k targeting young professionals. The aggressive pricing undercuts established players including HP Dell and Lenovo in the 60k-90k segment. Early reviews praise display quality and battery life while noting software support and service network as areas to watch.","engagement":0,"raw_metadata":g("Gadgets360","Xiaomi Launches Mi Notebook Pro Series in India at Aggressive Pricing")},
]

df = pd.DataFrame(RECORDS)
df = df[["date", "source", "category", "brand", "topic", "url", "author", "text", "engagement", "raw_metadata"]]
OUT.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(OUT, index=False)
print(f"Generated {len(df)} records -> {OUT}")
print(f"Sources: {df['source'].value_counts().to_dict()}")
print(f"Brands:  {df['brand'].value_counts().to_dict()}")
print(f"Dates:   {df['date'].min()} to {df['date'].max()}")
